{% set version = "2.0.0b3" %}

package:
  name: umami
  version: {{ version }}

source:
  url: https://github.com/TerrainBento/umami/archive/v{{ version }}.tar.gz
  sha256: 47aec7466f68bad1d8765821a374334c74d051d497e649bd16feaaaf31b6a804
  #  `openssl sha256 <file name>`.

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools

  run:
    - python >=3.6
    - scipy
    - numpy
    - landlab >=2.0.0b5, <2

test:
  requires:
    - pytest
    - pytest-cov
    - pytest-runner
    - pytest-datadir

  imports:
    - umami

  commands:
      - pytest --pyargs umami --doctest-modules -o doctest_optionflags="NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE"

about:
  home: https://umami.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Umami is a package for calculating objective functions or objective function components for landscape evolution modeling."

  description: |
      Umami is a package for calculating objective functions or objective
      function components for landscape evolution modeling. Umami offers two
      primary classes: a Residual which represents the difference between model
      and data, and Metric which is a calculated value on either model or data.
      A set of currently supported calculations are found in the
      umami.calculations submodule. Umami is built on top of the Landlab
      Toolkit and designed to work well with terrainbento.
  doc_url: https://umami.readthedocs.io
  dev_url: https://github.com/TerrainBento/umami

extra:
  recipe-maintainers:
    - kbarnhart
