travis:
  secure:
    BINSTAR_TOKEN: dE0Y/U3FvOrHk0SZvN8+kgng+aB67fJ7vZCyArvg10buCakO4qkvVGf+9NoGRuDQvak+yQ3hc1ByxUvjwIjEG2PIJjX6pe5Lsjrg1P3O4IeJIfbDisbb2LeavCiD1m8/XcjLyrGV8WCcGUQZxysSz2VCv/6eFwMId1WiyUdaolw0oxwr+EcaW6srcn/RPlWDT7VSSeUvQyjYOekMGgkvjjOQpKR2g2Gekck9jGroX2kAPgbpCdakQIM/F0Noq0zPV4uTDcIS3NVBio3dGazEcybZZByFf4nMKL/IsBRx8xhYnseVT4hUTuD5zjzRV8Qv76fSbo7nuPH5cmf6F9ar0Ovx7p2OlKfYXIzxntZ3KUnUm7ZAUTDh5EWj5a5vDauN64pUeo0jmWk5HzGPVzwGjdlra726wuj/ruNbLvOhnrgWq2fkpbGrFC7aYwm+kG2hy2gXdVXQvPsX3lYP6U9G1GFsZLbu3zTvyNQ+IdXoh+eILIxe1OEGCJCKSHs0UZiJGUNxj9GnaobQzWdAwUwkjvu/rDcA/1A9MPRZLaB1yYW5+Yuq225JG3VuFRYpB/BFXwuGC6Vfj3eJTtmCc175d1+rvWY+NqEwjEiQaJOaw+dGoFaXP+MgM7AmhcUZiqhqYACBqqzj72yCR9Q8w3i7Ib65oSkX78fKhU9kPZKR/lo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
